<a href="https://colab.research.google.com/github/Dykim991222/MLstudy/blob/main/%EB%94%A5%EB%9F%AC%EB%8B%9D%ED%9A%8C%EA%B7%80(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [6]:
# 컴퓨터에 있는 random seed table 은 컴퓨터 마다 다르므로
# 현재 실습하고 있는 파이썬코드를 재실행해도 같은 결과가 나오게끔
torch.manual_seed(1)

In [7]:
X_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [8]:
X_train, y_train

(tensor([[1.],
         [2.],
         [3.]]),
 tensor([[2.],
         [4.],
         [6.]]))

In [9]:
X_train.shape, y_train.shape

(torch.Size([3, 1]), torch.Size([3, 1]))

In [10]:
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
optimizer = optim.SGD([W,b], lr=0.001)

nb_epochs = 100
for epoch in range(nb_epochs+1):
  # 예측하기
  predict = X_train * W + b

  # 틀린 정도 계산하기
  cost = torch.mean((predict - y_train) ** 2)

  # 이전 step에서 계산된 gradient가 남아있을 수 있어서 초기화
  optimizer.zero_grad()

  # 틀린 정도(cost)를 기준으로  W, b를 얼마나 덜 틀리는지.
  # 기울기(gradient)를 계산한다.
  cost.backward()

  # 실제로 고치기. 계산된 gradient로 W, b값 수정하기
  optimizer.step()

  if epoch % 10 == 0:
    print("Epoch : {:4d}/{}, W:{:.3f}, b:{:.3f}, Cost: {:.6f}".format(
        epoch, nb_epochs, W.item(), b.item(), cost.item()
    ))

Epoch :    0/100, W:0.019, b:0.008, Cost: 18.666666
Epoch :   10/100, W:0.194, b:0.083, Cost: 14.949220
Epoch :   20/100, W:0.352, b:0.150, Cost: 11.975055
Epoch :   30/100, W:0.492, b:0.210, Cost: 9.595544
Epoch :   40/100, W:0.618, b:0.263, Cost: 7.691776
Epoch :   50/100, W:0.731, b:0.311, Cost: 6.168622
Epoch :   60/100, W:0.832, b:0.353, Cost: 4.949974
Epoch :   70/100, W:0.922, b:0.391, Cost: 3.974937
Epoch :   80/100, W:1.003, b:0.424, Cost: 3.194803
Epoch :   90/100, W:1.076, b:0.454, Cost: 2.570597
Epoch :  100/100, W:1.140, b:0.481, Cost: 2.071139


optimizer.zero_grad()가 필요한 이유

파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시키는 특징이 있음.

딥러닝 은 입력층과 출력층 사이에 여러개의 은닉층으로 이루어진 신경망이다. 층이 깊어질수록 모듈과 함수에 따른 하이퍼파라미터도 비례하여 많아지기에 이를 정확히 결정해 좋은 결과를 뱉어낼 수 있도록 하는것이 핵심.

Loss Function : 얼마나 틀리는지를 알게 하는 함수

Optimization : 최소값을 찾아가는 것. 최적화

Optimizer : 최적화 알고리즘

In [11]:
import torch
import torch.optim as optim
w = torch.tensor(2.0, requires_grad=True)
optimizer = optim.SGD([w], lr=0.01)
nb_epochs = 10
for epoch in range(nb_epochs+1):
  #optimizer.zero_grad()
  z = 2 * w
  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0


# 다중 선형 회귀를 matmul로 구현해보기

y = WX + WX + WX + b

# 특징

W, b를 직접 정의

**행렬곱(matmul)**으로 직접 선형 회귀식을 구현

신경망의 기본 구조(선형변환 → 오차 → 미분 → 옵티마이저 업데이트)를
가장 로우레벨에서 직접 체험함

실제로는 모델 구조가 단순할 때만 사용 가능

#  배우는 이유

신경망의 기본 동작 원리(Forward → Loss → Backward → Update)를 이해

선형 회귀, Perceptron, MLP 기본을 완전히 이해하게 됨

이후 복잡한 모델을 만들 때 “왜 이렇게 작동하지?” 를 파악하게 됨

즉, 딥러닝의 기초 체력을 만드는 데 필수.

In [12]:
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  80],
                               [96,  98,  100],
                               [73,  66,  70]])

y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [13]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [14]:
W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros((1), requires_grad=True)

In [22]:
# 값이 튈 수 있으니 정규화 진행하기.
x_mean = x_train.mean(dim=0)
x_std = x_train.std(dim=0)
x_norm = (x_train - x_mean) / x_std

y_mean = y_train.mean(dim=0)
y_std = y_train.std(dim=0)
y_norm = (y_train-y_mean) / y_std

# 가중치, 편향 설정
W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1000

for epoch in range(nb_epochs+1):
    predict = x_norm.matmul(W) + b
    cost = torch.mean((predict - y_norm) ** 2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch:4d}/{nb_epochs} Cost: {cost.item():.6f} "
              f"W: {W.squeeze().detach().tolist()} b: {b.item():.4f}")

Epoch    0/1000 Cost: 0.800000 W: [0.01576147973537445, 0.01520462241023779, 0.014837720431387424] b: 0.0000
Epoch  100/1000 Cost: 0.007364 W: [0.37443259358406067, 0.34778907895088196, 0.30188223719596863] b: -0.0000
Epoch  200/1000 Cost: 0.005482 W: [0.4034954309463501, 0.35840514302253723, 0.272542804479599] b: 0.0000
Epoch  300/1000 Cost: 0.004160 W: [0.4263972043991089, 0.3631184995174408, 0.24479912221431732] b: 0.0000
Epoch  400/1000 Cost: 0.003174 W: [0.44686025381088257, 0.36598533391952515, 0.2212372124195099] b: 0.0000
Epoch  500/1000 Cost: 0.002433 W: [0.46513915061950684, 0.36753329634666443, 0.20118972659111023] b: 0.0000
Epoch  600/1000 Cost: 0.001872 W: [0.4814404547214508, 0.36813485622406006, 0.18408076465129852] b: 0.0000
Epoch  700/1000 Cost: 0.001445 W: [0.4959574341773987, 0.36807018518447876, 0.16943778097629547] b: 0.0000
Epoch  800/1000 Cost: 0.001119 W: [0.5088695883750916, 0.3675490915775299, 0.156871497631073] b: 0.0000
Epoch  900/1000 Cost: 0.000869 W: [0.5

# 다중 선형 회귀를 nn과 F를 이용해서 학습해보자

# 특징

모델을 모듈화하여 관리 (계층 개수 늘리기 쉬움)

deep learning 전체 구조에 필요한 자동 독립성 & 유지보수 용이

레이어가 늘어나면 자동으로 파라미터 관리됨

실전 프로젝트에서는 대부분 이걸 씀

# 배우는 이유

CNN, RNN, Transformer 등 모든 딥러닝 구조를 이 방식으로 만들어야 함

실전 학습 코드 구성 능력을 얻게 됨

확장성 (레이어 추가, dropout, batchnorm 등) 제공

In [24]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [25]:
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  80],
                               [96,  98,  100],
                               [73,  66,  70]])

y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [30]:
model = nn.Linear(3, 1)

In [31]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [27]:
# x_train은 3개의 특성, 5개의 데이터.
# 따라서 열 기준으로 평균, 표준편차 구하고 정규화
x_mean = x_train.mean(dim=0)
x_std = x_train.std(dim=0)
x_norm = (x_train - x_mean) / x_std

y_mean = y_train.mean(dim=0)
y_std = y_train.std(dim=0)
y_norm = (y_train - y_mean) / y_std

In [35]:
optimizer = optim.Adam(model.parameters(), lr=1e-5)
nb_epochs = 1000

for epoch in range(nb_epochs+1):
  predict = model(x_train)
  cost = F.mse_loss(predict, y_norm)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{}, Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/1000, Cost: 0.176423
Epoch  100/1000, Cost: 0.176324
Epoch  200/1000, Cost: 0.176226
Epoch  300/1000, Cost: 0.176129
Epoch  400/1000, Cost: 0.176032
Epoch  500/1000, Cost: 0.175935
Epoch  600/1000, Cost: 0.175839
Epoch  700/1000, Cost: 0.175743
Epoch  800/1000, Cost: 0.175646
Epoch  900/1000, Cost: 0.175550
Epoch 1000/1000, Cost: 0.175453


임의의 데이터로 학습된 모델에 넣어 예측해보기

In [37]:
# 기존 값들
x_mean = x_train.mean(dim=0)
x_std = x_train.std(dim=0)

y_mean = y_train.mean()
y_std = y_train.std()

# 새로운 입력
new_var = torch.FloatTensor([[73, 80, 75]])

# 1) 입력 정규화
new_var_norm = (new_var - x_mean) / x_std

# 2) 모델 예측
pred_y_norm = model(new_var_norm)

# 3) 역정규화
pred_y = pred_y_norm * y_std + y_mean

print("예측된 실제 y값:", pred_y.item())

예측된 실제 y값: 80.26888275146484


# 다중 선형회귀 클래스형태로 구현해보기

In [38]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [39]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [43]:
class MultivariateLinearRegression(nn.Module):
  def __init__(self):
    super().__init__() # nn.Module 상속
    # super()로 기반 클래스(부모 클래스) 를 초기화해줌으로써,
    # 기반 클래스의 속성을 subclass가 받아오도록 한다.
    # (초기화를 하지 않으면, 부모 클래스의 속성 사용 X)
    self.linear = nn.Linear(3, 1)

  def forward(self, x):
    return self.linear(x)

In [44]:
model = MultivariateLinearRegression()
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [47]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
  # 모델
  prediction = model(x_train)

  # cost 꼐산
  cost = F.mse_loss(prediction, y_train)
  optimizer.zero_grad() # gradient 를 0으로 초기화
  cost.backward() # cost function  미분하여 gradient 계산
  optimizer.step() # W와 b 업데이트

  if epoch % 500 == 0:
    print('Epoch {}/{} cost {:.3f} '.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch 0/2000 cost 0.432 
Epoch 500/2000 cost 0.415 
Epoch 1000/2000 cost 0.401 
Epoch 1500/2000 cost 0.389 
Epoch 2000/2000 cost 0.379 


# 미니배치 학습을 구현해보자

In [48]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [50]:
from torch.utils.data import TensorDataset # 텐서데이터셋
from torch.utils.data import DataLoader # 데이터로더

In [51]:
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  90],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [54]:
dataset = TensorDataset(x_train, y_train)
'''
[
  ([73, 80, 75], [152]),
  ([93, 88, 93], [185]),
  ([89, 91, 90], [180]),
  ([96, 98, 100], [196]),
  ([73, 66, 70], [142]),
]
입력과 정답을 튜플 형태(입력->정답) 형태로 학습
'''
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)
'''
Batch 1:
([73, 80, 75], [152])
([93, 88, 93], [185])
Batch 2:
([89, 91, 90], [180])
([96, 98, 100], [196])
Batch 3:
([73, 66, 70], [142])
'''

'\nBatch 1:\n([73, 80, 75], [152])\n([93, 88, 93], [185])\nBatch 2:\n([89, 91, 90], [180])\n([96, 98, 100], [196])\nBatch 3:\n([73, 66, 70], [142])\n'

In [55]:
model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [60]:
nb_epochs = 3
for epoch in range(nb_epochs+1):
  for batch_idx, samples in enumerate(dataloader):
    print(batch_idx)
    print(samples)

0
[tensor([[73., 80., 75.],
        [73., 66., 70.]]), tensor([[152.],
        [142.]])]
1
[tensor([[93., 88., 93.],
        [89., 91., 90.]]), tensor([[185.],
        [180.]])]
2
[tensor([[ 96.,  98., 100.]]), tensor([[196.]])]
0
[tensor([[73., 80., 75.],
        [89., 91., 90.]]), tensor([[152.],
        [180.]])]
1
[tensor([[73., 66., 70.],
        [93., 88., 93.]]), tensor([[142.],
        [185.]])]
2
[tensor([[ 96.,  98., 100.]]), tensor([[196.]])]
0
[tensor([[ 96.,  98., 100.],
        [ 73.,  66.,  70.]]), tensor([[196.],
        [142.]])]
1
[tensor([[73., 80., 75.],
        [89., 91., 90.]]), tensor([[152.],
        [180.]])]
2
[tensor([[93., 88., 93.]]), tensor([[185.]])]
0
[tensor([[73., 80., 75.],
        [93., 88., 93.]]), tensor([[152.],
        [185.]])]
1
[tensor([[73., 66., 70.],
        [89., 91., 90.]]), tensor([[142.],
        [180.]])]
2
[tensor([[ 96.,  98., 100.]]), tensor([[196.]])]


In [63]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
  for batch_idx, samples in enumerate(dataloader):
    x_train, y_train = samples
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

  if epoch % 400 == 0:
    print("Epoch : {}/{}, Cost : {:.3f}".format(
        epoch, nb_epochs, cost.item()
    ))

Epoch : 0/2000, Cost : 0.615
Epoch : 400/2000, Cost : 0.543
Epoch : 800/2000, Cost : 0.684
Epoch : 1200/2000, Cost : 0.055
Epoch : 1600/2000, Cost : 0.593
Epoch : 2000/2000, Cost : 0.113


### 실습) 다음 조건을 만족하는 다중 선형회귀 학습을 짜시오

1. 데이터는 아래 데이터 그대로 사용할 것
2. 그에 맞는 다중 선형회귀를 클래스 형태로 짤 것.
3. 미니배치사이즈 4
4. 에폭 100
5. 옵티마이저, loss 마음대로 선택. 단, 성능은 신경쓰지 말 것.
6. import는 마음대로 넣을 것.
7. x_test 변수를 이용해 예측해서 결과를 출력하고 기울기함수를 해제하시오: detach 사용

In [79]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

x_train  =  torch.FloatTensor([[73,  80,  75, 88],
                               [93,  88,  93, 87],
                               [89,  91,  90, 95],
                               [96,  98,  93, 95],
                               [73,  66,  70, 77],
                               [77,  82,  75, 86],
                               [88,  75,  91, 90]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142], [151], [155]])

x_mean = x_train.mean(dim=0)
x_std = x_train.std(dim=0)
x_norm = (x_train - x_mean) / x_std

y_mean = y_train.mean(dim=0)
y_std = y_train.std(dim=0)
y_norm = (y_train - y_mean) / y_std

dataset = TensorDataset(x_norm, y_norm)
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

class MultivariateLinearRegression(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(4, 1)

  def forward(self, x):
    return self.linear(x)

model = MultivariateLinearRegression()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-6)

nb_epochs = 10
for epoch in range(nb_epochs+1):
  for batch_idx, samples in enumerate(dataloader):

    x_train2, y_train2 = samples
    prediction = model(x_train2)
    cost = F.mse_loss(prediction, y_train2)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

  if epoch % 2 == 0:
    print("Epoch : {}/{}, Cost : {:.3f}".format(
        epoch, nb_epochs, cost.item()
    ))

Epoch : 0/10, Cost : 0.644
Epoch : 2/10, Cost : 1.024
Epoch : 4/10, Cost : 0.403
Epoch : 6/10, Cost : 0.826
Epoch : 8/10, Cost : 1.383
Epoch : 10/10, Cost : 0.580


In [80]:
x_test = torch.FloatTensor([[85, 90, 95, 93]])
x_test_norm = (x_test - x_mean) / x_std
y_pred_norm = model(x_test_norm)
y_pred = y_pred_norm * y_std + y_mean

# detach 사용해서 gradient 연결 끊고 값만 가져오기
y_pred_value = y_pred.detach().item()

print("입력값:", x_test.tolist())
print("예측값:", y_pred_value)


입력값: [[85.0, 90.0, 95.0, 93.0]]
예측값: 158.80560302734375
